pipeline:
  identifier: Build_tonydalhoff_cloudflare_workers_1750031128280
  name: Build cloudflare-workers
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1750031042995
        repoName: tonydalhoff/cloudflare-workers
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Run Vitest
                  spec:
                    shell: Sh
                    command: npm run tests
                  timeout: ""
                  type: Run
                  description: Runs Vitest tests
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
