pipeline:
  identifier: Build_tonydalhoff_cloudflare_workers_1750031128280
  name: Build cloudflare-workers
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1750031042995
        repoName: tonydalhoff/cloudflare-workers
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Vitest Tests
                  spec:
                    shell: Bash
                    command: |-
                      #!/bin/bash
                      echo "Detecting changed directories..."

                      # Set your base branch (e.g., for PRs)
                      BASE_BRANCH="origin/main"

                      # Fetch base branch
                      git fetch origin main

                      # Find top-level subdirectories in packages/ with changes
                      CHANGED_DIRS=$(git diff --name-only $BASE_BRANCH...HEAD | cut -d/ -f1)

                      echo "Changed directories:"
                      echo "$CHANGED_DIRS"

                      # Run tests in each changed dir
                      for dir in $CHANGED_DIRS; do
                        echo "Running tests in $dir"
                        cd $dir
                        npm install
                        npm test
                        cd - > /dev/null
                      done
                  timeout: ""
                  type: Run
                  description: Runs Vitest tests
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
